### ISSUE TITLE
[Prototype] Inventory Management Page

### ISSUE THREAD

**Issue by noahshoap** [jimventory/Frontend#4]
# Inventory Management Page

## Description
As a developer, I would like to have a rough idea of what we need to implement eventually.  A prototype, either drawn, created with a UX tool, or manually implemented would be useful.

## Acceptance Criteria
- Prototype created
- Team feedback

**Comment by vbroda17** [comment]
![Image](https://github.com/jimventory/Frontend/assets/101155730/29a9d36f-4ac8-4dcb-ae30-43f296b0c7c7)
