### ISSUE TITLE
Investigate useEffect Problem

### ISSUE THREAD

**Issue by noahshoap** [jimventory/Frontend#43]
# Investigate useEffect Problem
As a developer, I want to avoid code running more than it should.  Currently, in some components that use the `useEffect` hook, there seems to be an issue where they run twice or even more.  This is likely either caused by something causing a re-render or something wrong with the `useEffect` dependency array.

## Acceptance Criteria
- Investigate and reproduce issue
- Resolve across codebase

**Comment by noahshoap** [comment]
I believe this issue has survived the refactor, although I have not confirmed that.

**Comment by vbroda17** [comment]
I found this in the [React dev notes](https://react.dev/reference/react/useEffect#my-effect-runs-twice-when-the-component-mounts) that seems to imply this is a common and desired effect that react specifically does to insure that logic is correct. As long as this does not effect logic everything should be fine, I will still go through the code and work flow to make sure of this though.
