### ISSUE TITLE
Add Streamline Logo to bottom of all the pages

### ISSUE THREAD

**Issue by jhulen** [jimventory/Frontend#51]
# Add Streamline Logo to bottom of all the pages
As a developer, I want our pages to have a consistent look and feel.  We should have our logo as a footer for all pages.

## Acceptance Criteria
- Add the StreamLine logo footer at the bottom of all the pages for uniformity.  See existing pages with logo footer for reference.

**Comment by noahshoap** [comment]
Just a thought: rather than modifying the pages themselves to have the footer, investigate making a `LogoFooter` component that just renders the footer, and add this to `App.tsx`.

If this works, let's take that approach.
