### ISSUE TITLE
Business View Page

### ISSUE THREAD

**Issue by noahshoap** [jimventory/Frontend#8]
# Business View Page

## Description
As a user, when I login to my business I want to see information relevant to my business' inventory.

## Acceptance Criteria
- Reference prototype from earlier.
- Business view page created.
- Basic functionality, assuming back-end work is completed.

**Comment by vbroda17** [comment]
Right now a genera layout and styling has been done. I am assuming it will be altered and cleaned up more. As well I have not added API integration just yet

![Image](https://github.com/jimventory/Frontend/assets/101155730/92df8b6e-4510-449c-b094-5e60b6b291e0)
